site:
  title: My Notes
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://jucosorin.my-notes/
  start_page: lxd::index.adoc
content:
  sources:
    - url: https://jucosorin.my-notes.git
      start_path: docs/lxd
      branches: main
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
