= Fix microk8s not staring because of missing AppArmor profiles
:hide-uri-scheme:
:example-caption!:
:source-highlighter: highlight.js

After a host machine or lxd machine restart check the status of the microk8s application by running the following command:

[source,console]
----
$ juju status
----

If the status looks like the following:

[source]
.Example output from a failed microk8s application
--
Model        Controller  Cloud/Region         Version  SLA          Timestamp
k8s-cluster  microcloud  rpi-cluster/default  3.2.3    unsupported  20:06:28+02:00

App              Version  Status  Scale  Charm     Channel    Rev  Exposed  Message
microk8s         1.28.2   error       1  microk8s  1.28/edge  217  yes      hook failed: "config-changed"
microk8s-worker  1.28.2   error       2  microk8s  1.28/edge  217  no       hook failed: "update-status"

Unit                Workload  Agent  Machine  Public address                          Ports      Message
microk8s-worker/0   error     idle   1        fdc2:82ea:298c:4ac9:216:3eff:fe6d:2903             hook failed: "update-status"
microk8s-worker/1*  error     idle   2        fdc2:82ea:298c:4ac9:216:3eff:fee9:6c0e             hook failed: "update-status"
microk8s/0*         error     idle   0        192.168.88.41                           16443/tcp  hook failed: "config-changed"

Machine  State    Address                                 Inst id        Base          AZ  Message
0        started  192.168.88.41                           juju-e8f027-0  ubuntu@22.04      Running
1        started  fdc2:82ea:298c:4ac9:216:3eff:fe6d:2903  juju-e8f027-1  ubuntu@22.04      Running
2        started  fdc2:82ea:298c:4ac9:216:3eff:fee9:6c0e  juju-e8f027-2  ubuntu@22.04      Running
--

Then the microk8s application is in a failed state. 

Ssh to each unit in the cluster by running the following command:

[source,console]
----
$ juju ssh microk8s/<unit-id>
----

or 

[source,console]
----
$ juju ssh microk8s-worker/<unit-id>
----

While logged into the unit, run the following command to get the status of the microk8s application:

[source,console]
----
$ sudo microk8s status
----

If the status looks like the following:

[source]
.Example output from a failed microk8s application
--
missing profile snap.microk8s.microk8s.
Please make sure that the snapd.apparmor service is enabled and started
--

== Quick fix

Issue the following command to enable and start the snapd.apparmor service:

[source,console]
----
$ sudo apparmor_parser --add /var/lib/snapd/apparmor/profiles/snap.microk8s.*
----

Then run the following command to restart the microk8s application:

[source,console]
----
$ sudo microk8s stop
$ sudo microk8s start
----

In order to fix the failed hooks restart the individual units (LXD in our case) by running the following command:

[source,console]
----
$ lxd restart <instance-name>
----

Finally, mark unit errors as resolved by running the following command: 

[source,console]
----
$ juju resolve --all
----

== Make the solution permanent

The easiest solution is to copy AppArmor profiles to the host operating system.

Run the following commands from the MacOS lxc client.

First run *juju status* and get the name of lxc machine that is runnning a kubernetes worker node. For instance _juju-e8f027-1_ . Create a temporary directory inside this node.

[source,console]
----
$ lxc exec juju-e8f027-1 -- mkdir /tmp/microk8s
----

Copy microk8s AppArmor profiles in this folder.

[source,console]
----
$ lxc exec juju-e8f027-1 -- find /var/lib/snapd/apparmor/profiles/ -name "snap.microk8s.*" -exec cp {} /tmp/microk8s/ \;
----

List files inside the guest operating system.

[source,console]
----
$ lxc exec juju-e8f027-1 -- ls /tmp/microk8s
----

Next log into each LXD machine in the LXD cluster and run the following commands.

[source,console]
----
$ sudo lxc file pull -r juju-e8f027-1/tmp/microk8s /etc/apparmor.d/
----

List files copied to the host operating system.

[source,console]
----
$ ls /etc/apparmor.d/microk8s/
----

Read microk8s AppArmor profiles inside the host operating system.

[source,console]
----
$ sudo apparmor_parser --replace /etc/apparmor.d/microk8s/
----

Check AppArmor status to see that the profiles have been loaded.

[source,console]
----
$ sudo aa-status
----

These profiles will be read automatically after the host operating system reboots.

NOTE: Solution taken from https://sleeplessbeastie.eu/2020/07/20/how-to-deal-with-missing-apparmor-profiles-for-microk8s-on-lxd/